"""Initial migration

Revision ID: a3e2e6e5df07
Revises: 
Create Date: 2025-08-25 19:53:38.646163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e2e6e5df07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('session_seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('content_value_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('delivery_cost_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_session_id'), 'parcels', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_session_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
